using BackToBinding.Data;
using BackToBinding.Utils;
using System.Text;

namespace BackToBinding
{
    internal class DataTarget
    {
        private string _outputDir;

        public List<DataAlias> Aliases { get; set; }
        public List<DataStruct> Structs { get; set; }
        public List<DataEnum> Enums { get; set; }

        public void Translate(string outputDir)
        {
            Aliases.ForEach(alias => alias.Resolve());

            _outputDir = outputDir;

            Structs.ForEach(st => Write(st.Name, st));
            Enums.ForEach(e => Write(e.Name, e));
        }

        public void Write(string name, IData dataObj)
        {
            var content = new StringBuilder();
            content.AutogeneratedInfo();

            dataObj.AsText(0, content);

            File.WriteAllText(Path.Combine(_outputDir, $"{name}.back"), content.ToString());
        }
    }
}
