using BackToBinding.Data;
using BackToBinding.Utils;
using System.Text;

namespace BackToBinding
{
    internal class DataTarget
    {
        private string _outputDir;

        public List<DataStruct> Structs { get; set; }
        public List<DataEnum> Enums { get; set; }

        public void Translate(string outputDir)
        {
            _outputDir = outputDir;
            Structs.ForEach(st => Write(st.Name, st));
            Enums.ForEach(e => Write(e.Name, e));
        }

        public void Write(string name, IData dataObj)
        {
            var content = new StringBuilder();
            content.AppendLine("// ! ! ! AUTOGENERATED CODE - DO NOT MODIFY ! ! !");
            content.AppendLine("// This code was autogenerated by BackToBinding.");
            content.AppendLine("// Please report issues at our repository: https://github.com/DasLixou/BackToBinding");
            content.AppendLine("// ! ! ! AUTOGENERATED CODE - DO NOT MODIFY ! ! !");

            dataObj.AsText(0, content);

            File.WriteAllText(Path.Combine(_outputDir, $"{name}.back"), content.ToString());
        }
    }
}
