using System.Text;

namespace BackToBinding.Utils
{
    public static class StringBuilderExtension
    {
        public static void Indent(this StringBuilder builder, int indent)
        {
            builder.Append(new string('\t', indent));
        }

        public static void Line(this StringBuilder builder)
        {
            builder.AppendLine("");
        }

        public static void AutogeneratedInfo(this StringBuilder builder)
        {
            builder.AppendLine("// ! ! ! AUTOGENERATED CODE - DO NOT MODIFY ! ! !");
            builder.AppendLine("// This code was autogenerated by BackToBinding.");
            builder.AppendLine("// Please report issues at our repository: https://github.com/DasLixou/BackToBinding");
            builder.AppendLine("// ! ! ! AUTOGENERATED CODE - DO NOT MODIFY ! ! !");
            builder.Line();
        }

        public static void Documentate(this StringBuilder builder, int indent, string doc)
        {
            builder.AppendLine("/**");
            builder.Indent(indent);
            builder.AppendLine("* " + doc);
            builder.Indent(indent);
            builder.AppendLine("*/");
        }
    }
}
